#' Generate default inputs for TreeQSM
#'
#' This function generates a range of inputs for TreeQSM. Please
#' note that this function merely exists demonstate the correct
#' format of parameters, and it follows the parameters used in
#' Cannon et al. 202X article.
#' @examples
#' print(default_qsm_inputs())
#' @export
default_qsm_inputs = function() {
  pars = list(PatchDiam1 = c(0.05, 0.10, 0.15),
              PatchDiam2Min = c(0.03, 0.04, 0.05),
              PatchDiam2Max = c(0.12, 0.14, 0.16),
              lcyl = c(0.33, 0.50, 0.75))
  return(pars)
}


#' Convert `LAS` object to MATLAB .mat
#'
#' This function converts a `LAS` object to a point cloud, and saves
#' as a .mat MATLAB object for input to `[run_qsm]`.
#'
#' @param las a `LAS` object representing single segmented tree with
#' foliage removed.
#' @param output_mat character - a file path ending in `.mat` representing
#' output location of file. Defaults to temporary location
#' @importFrom dplyr select
#' @importFrom R.matlab writeMat
#' @examples
#' library(lidR)
#' las = readLAS(system.file("extdata", "tree_0744.laz", package="tReeTraits"))
#' las_cleaned = clean_las(las)
#' las_to_mat(las_cleaned)
#' @export
las_to_mat = function(las, output_mat = tempfile(fileext = '.mat')) {
  if(file.exists(output_mat)) stop(paste0(output_mat, ' already exists'))
  pc = dplyr::select(las@data, X,Y,Z)
  R.matlab::writeMat(output_mat, tree=as.matrix(pc))
  if(file.exists(output_mat)) cat('.mat export completed:', output_mat)
  return(output_mat)
}


#' Generate QSM using TreeQSM Matlab script from inputs
#'
#' This function generates a QSM using TreeQSM code in Matlab. The code generates
#' a Matlab script script (.m) capable of running TreeQSM based on input data
#' and parameters. Requires that Matlab be
#' installed, the path known, and appropriate Matlab extensions installed
#' See [Readme.md]('../README.md') for details.
#' @param tree_mat character - path to .mat file representing tree point cloud.
#' Can be created using [`las_to_mat()`].
#' @param unique_id character - ID to use for saving filenames
#' @param output_results character - path to location for output results
#' @param TreeQSM_directory character - path to location of TreeQSM folder
#' @param parameter_inputs list - parameter inputs generated by or modified
#' from `[default_qsm_inputs()]`. Must contain numeric vectors `PatchDiam1`,
#' `PatchDiam2Min`, `PatchDiam2Max`, and `lycl`.
#' See [`TreeQSM`](http://github.com/InverseTampere/TreeQSM)documentation for more information on input parameters.
#' @param template_script character - path to dynamic input script template
#' for generated matlab code. Defaults to file installed with library, but
#' exposed to user for customization
#' @param exit boolean - indicates whether to close matlab after run
#' @param wait boolean - indicates whether to wait for matlab to complete before
#' continuing
#' @importFrom readtext readtext
#' @examples
#' library(lidR)
#' las = readLAS(system.file("extdata", "tree_0744.laz", package="tReeTraits"))
#' las = filter_poi(las, Intensity > 44000) # remove foliage returns
#' las = clean_las(las)
#' tree_mat = las_to_mat(las)
#' run_qsm(tree_mat = tree_mat, unique_id = 'Tree_0744',
#'     output_results = 'R:/landscape_ecology/projects/canopy-traits/qsm-results/',
#'     TreeQSM_directory = 'R:/landscape_ecology/projects/canopy-traits/docs/TreeQSM/')
#' @export
run_qsm = function(
    tree_mat, unique_id, output_results,
    TreeQSM_directory,
    parameter_inputs = default_qsm_inputs(),
    wait=TRUE, exit = TRUE, overwrite=FALSE,
    template_script = system.file("extdata", "dynamic_QSM_script_template.m", package="tReeTraits")) {

  out_file = paste0(output_results, '/', unique_id, '_qsm.mat')
  if(file.exists(out_file)) {
    if(overwrite) unlink(out_file)
    if(!overwrite) stop(paste0('Output file already exists. Use `overwrite = TRUE`
    to overwrite.\n', out_file))
  }

  # Create mat lab script with appropriate fields substituted
  output_script = tempfile(fileext = '.m')
  txt = suppressWarnings(readtext::readtext(template_script)$text)
  tree_mat = gsub('\\\\', '/', tree_mat)
  txt = gsub('%%TREE_MAT_PATH%%', gsub('.mat$', '', tree_mat), txt)
  txt = gsub('%%TREE_ID%%', unique_id, txt)
  txt = gsub('%%TREE_QSM_DIRECTORY%%', TreeQSM_directory, txt)
  txt = gsub('%%OUT_DIR%%', output_results, txt)
  txt = gsub('%%N_CORES%%', 8, txt) #this bit doesn't seem to work, runs 8 regardless
  # add parameters to script
  formatted_inputs = lapply(parameter_inputs, function(x) paste0(x, collapse=', '))
  txt = gsub('%%INPUTS_PATCHDIAM1%%', formatted_inputs$PatchDiam1, txt)
  txt = gsub('%%INPUTS_PATCHDIAM2MIN%%', formatted_inputs$PatchDiam2Min, txt)
  txt = gsub('%%INPUTS_PATCHDIAM2MAX%%', formatted_inputs$PatchDiam2Max, txt)
  txt = gsub('%%INPUTS_LCYL%%', formatted_inputs$lcyl, txt)
  writeLines(txt, con = output_script) # save to fiel to run in matlab
  cat('TreeQSM Matlab script saved to:\n', output_script, '\n')

  #run in matlab
  options = '-nosplash -nodesktop -r '
  if(exit) cmd = paste0("matlab ", options, "\"run('", gsub("\\\\", "//", output_script), "'); exit\"")
  if(!exit) cmd = paste0("matlab ", options, "\"run('", gsub("\\\\", "//", output_script), "');\"")
  cat('Running TreeQSM from command line:\n')
  print(cmd)
  system(cmd, intern=TRUE)
  out_file = paste0(output_results, '/', unique_id, '_qsm.mat')
  if(wait) while(!file.exists(out_file)) Sys.sleep(1)
  if(file.exists(out_file)) message('QSM file created successfully\n', out_file)
  return(out_file)
}



#mat lab instructions
#Must install parallel computing toolbox
#https://www.mathworks.com/matlabcentral/answers/4707-how-can-i-download-parallel-computing-toolbox
#Must install Statistics and Machine Learning toolbox
#https://www.mathworks.com/products/statistics.html


# function to make JPGS




# internal function to check for valid Tree QSM parameter inputs
valid_qsm_inputs = function(inputs) {
  # check if its a list
  if(!is.list(inputs)) {
    stop('QSM inputs must be a list. See `?default_qsm_inputs() for examples`')
  }
  # check if all 4 parameters are specified
  if(length(inputs)!=4) {
    stop('Four QSM inputs must be specified See `?default_qsm_inputs() for examples`')
  }
  # check if all names are valid
  valid_names = names(default_qsm_inputs())
  if(all(valid_names %in% names(inputs)) == FALSE) {
    stop('Invalid parameter names. See `?default_qsm_inputs() for examples`')
  }
  #check if all numeric
  if(all(sapply(inputs, function(x) is.numeric(x))) == FALSE) {
    stop('Parameters must be numeric. See `?default_qsm_inputs() for examples`')
  }
  #check if all are specified
  if(all(sapply(inputs, function(x) length(x)>1)) == FALSE) {
    stop('At least one value for each parameter must be specified. See
         `?default_qsm_inputs() for examples`')
  }
  #check that none are NA
  if(all(sapply(inputs, function(x) all(!is.na(x)))) == FALSE) {
    stop('No NA values allowed in parameter specification. See
         `?default_qsm_inputs() for examples`')
  }
  #check that none are Inf
  if(all(sapply(inputs, function(x) all(!is.infinite(x)))) == FALSE) {
    stop('No Inf values allowed in parameter specification. See
         `?default_qsm_inputs() for examples`')
  }
  return(TRUE)
}
